baseURL: https://santosh-kumar-perumal.netlify.app/

languageCode: en-us
title: "Santosh Kumar Perumal"

# Use Hugo modules to add theme
module:
  imports:
  - path: github.com/hugo-toha/toha/v4
  mounts:
  - source: static/files
    target: static/files
  - source: ./node_modules/flag-icon-css/flags
    target: static/flags
  - source: ./node_modules/@fontsource/mulish/files
    target: static/files
  - source: ./node_modules/katex/dist/fonts
    target: static/fonts

# Site parameters
params:
  # Background image of the landing page
  background: /images/site/background.jpg

  # Provide logos for your site. The inverted logo will be used in the initial
  # transparent navbar and the main logo will be used in the non-transparent navbar.
  logo:
    favicon: /images/site/favicon.png

  # GitHub repo of your site
  gitRepo: https://github.com/hugo-toha/hugo-toha.github.io
  # Default branch of your Git repo
  gitBranch: main

  # Configure the number of section title visible in the top navbar
  topNavbar:
    maxVisibleSections: 5

# Provide footer configuration.
footer:
    enable: false
    # You can provide your custom footer template using this option.
    # Put your template in "layouts/partials" folder of your repo.
    template: footer.html
    # Show/hide navigation in the footer. Default is "true".
    navigation:
      enable: false
      # show custom menus in the footer
      customMenus: false
    # Show/hide "Contact Me" section in the footer. Default is "true".
    contactMe:
      enable: false
    # Show/hide credentials section in the footer. Default is "true".
    credentials:
      enable: false
    # Show/hide disclaimer notice in the footer. Default is "false".
    disclaimer:
      enable: false




